name=RATGDO
version=0.0.1
author=Paul Wieland
maintainer=Cody <codysorgenfrey@gmail.com>
category=Communication
url=https://github.com/codysorgenfrey/mqtt-ratgdo
architectures=esp32, esp8266
includes=ratgdo.h